### ISSUE TITLE
Video Devil Custom

### ISSUE THREAD

**Issue by imurreflection** [FAlbanni/videoDevilCustom#1]
Hi, i haven't tried it yet but it seems to be a great improvement. Can i request you to look at ultimate white team plugin and try implementing this feature there. UWC is by far the best plugin and Videodevil doesn't stand anywhere. There are extremely helpful and polite independent developer always helps not like arrogant people here.

**Comment by FAlbanni** [comment]
It can be easily done for UWC too ofc! At some random spare time I might do it.
